imports:
    - php
tools:
    external_code_coverage: true
    php_code_sniffer: true
    php_sim: true
    php_changetracking: true
    php_cs_fixer:
        config: { level: psr2 }
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
filter:
    excluded_paths: [Tests/*]
checks:
    php:
        code_rating: true
